#!/bin/bash

set -ex -o pipefail

. /env.sh

if ovsdb-tool check-cluster "$db" | grep "shows that the server has left the cluster"; then
	echo "Server has already left the cluster"
	exit 0
fi

/dbserver &

while [ ! -e "${db_ctl}" ]; do
	if [ ! -f /proc/$!/comm ]; then
		echo "ovsdb-server failed to start"
		exit 1
	fi

	echo "Waiting for ovsdb-server to start"
	sleep 1
done

[ "$has_left" == 1 ] || ovs-appctl -t "${db_ctl}" cluster/leave "${db_name}"
ovs-appctl -t "${db_ctl}" exit
