/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group ovn --version v1beta1 --kind OVNDBCluster --programmatic-validation --defaulting
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
	topologyv1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
	"k8s.io/apimachinery/pkg/util/validation/field"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// OVNDBClusterDefaults -
type OVNDBClusterDefaults struct {
	NBContainerImageURL string
	SBContainerImageURL string
}

var ovnDbClusterDefaults OVNDBClusterDefaults

// log is for logging in this package.
var ovndbclusterlog = logf.Log.WithName("ovndbcluster-resource")

// SetupOVNDBClusterDefaults - initialize OVNDBCluster spec defaults for use with either internal or external webhooks
func SetupOVNDBClusterDefaults(defaults OVNDBClusterDefaults) {
	ovnDbClusterDefaults = defaults
	ovndbclusterlog.Info("OVNDBCluster defaults initialized", "defaults", defaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *OVNDBCluster) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-ovn-openstack-org-v1beta1-ovndbcluster,mutating=true,failurePolicy=fail,sideEffects=None,groups=ovn.openstack.org,resources=ovndbclusters,verbs=create;update,versions=v1beta1,name=movndbcluster.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &OVNDBCluster{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *OVNDBCluster) Default() {
	ovndbclusterlog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this OVNDBCluster spec
func (spec *OVNDBClusterSpec) Default() {
	if spec.ContainerImage == "" {
		if spec.DBType == NBDBType {
			spec.ContainerImage = ovnDbClusterDefaults.NBContainerImageURL
		} else if spec.DBType == SBDBType {
			spec.ContainerImage = ovnDbClusterDefaults.SBContainerImageURL
		}
	}
	spec.OVNDBClusterSpecCore.Default()
}

// Default - set defaults for this OVNDBCluster core spec (this version is called by OpenStackControlplane webhooks)
func (spec *OVNDBClusterSpecCore) Default() {
	// nothing here yet
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-ovn-openstack-org-v1beta1-ovndbcluster,mutating=false,failurePolicy=fail,sideEffects=None,groups=ovn.openstack.org,resources=ovndbclusters,verbs=create;update,versions=v1beta1,name=vovndbcluster.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &OVNDBCluster{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *OVNDBCluster) ValidateCreate() (admission.Warnings, error) {
	ovndbclusterlog.Info("validate create", "name", r.Name)

	errors := field.ErrorList{}
	basePath := field.NewPath("spec")

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	if r.Spec.TopologyRef != nil {
		if err := topologyv1.ValidateTopologyNamespace(r.Spec.TopologyRef.Namespace, *basePath, r.Namespace); err != nil {
			errors = append(errors, err)
		}
	}
	if len(errors) != 0 {
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "ovn.openstack.org", Kind: "OVNDBCluster"},
			r.Name, errors)
	}
	return nil, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *OVNDBCluster) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	ovndbclusterlog.Info("validate update", "name", r.Name)

	errors := field.ErrorList{}
	basePath := field.NewPath("spec")

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	if r.Spec.TopologyRef != nil {
		if err := topologyv1.ValidateTopologyNamespace(r.Spec.TopologyRef.Namespace, *basePath, r.Namespace); err != nil {
			errors = append(errors, err)
		}
	}
	if len(errors) != 0 {
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "ovn.openstack.org", Kind: "OVNDBCluster"},
			r.Name, errors)
	}
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *OVNDBCluster) ValidateDelete() (admission.Warnings, error) {
	ovndbclusterlog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}
