//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/openstack-k8s-operators/lib-common/modules/common/condition"
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNController) DeepCopyInto(out *OVNController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNController.
func (in *OVNController) DeepCopy() *OVNController {
	if in == nil {
		return nil
	}
	out := new(OVNController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNControllerDefaults) DeepCopyInto(out *OVNControllerDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNControllerDefaults.
func (in *OVNControllerDefaults) DeepCopy() *OVNControllerDefaults {
	if in == nil {
		return nil
	}
	out := new(OVNControllerDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNControllerList) DeepCopyInto(out *OVNControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OVNController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNControllerList.
func (in *OVNControllerList) DeepCopy() *OVNControllerList {
	if in == nil {
		return nil
	}
	out := new(OVNControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNControllerSpec) DeepCopyInto(out *OVNControllerSpec) {
	*out = *in
	in.OVNControllerSpecCore.DeepCopyInto(&out.OVNControllerSpecCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNControllerSpec.
func (in *OVNControllerSpec) DeepCopy() *OVNControllerSpec {
	if in == nil {
		return nil
	}
	out := new(OVNControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNControllerSpecCore) DeepCopyInto(out *OVNControllerSpecCore) {
	*out = *in
	in.ExternalIDS.DeepCopyInto(&out.ExternalIDS)
	if in.NicMappings != nil {
		in, out := &in.NicMappings, &out.NicMappings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNControllerSpecCore.
func (in *OVNControllerSpecCore) DeepCopy() *OVNControllerSpecCore {
	if in == nil {
		return nil
	}
	out := new(OVNControllerSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNControllerStatus) DeepCopyInto(out *OVNControllerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNControllerStatus.
func (in *OVNControllerStatus) DeepCopy() *OVNControllerStatus {
	if in == nil {
		return nil
	}
	out := new(OVNControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNDBCluster) DeepCopyInto(out *OVNDBCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNDBCluster.
func (in *OVNDBCluster) DeepCopy() *OVNDBCluster {
	if in == nil {
		return nil
	}
	out := new(OVNDBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNDBCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNDBClusterDefaults) DeepCopyInto(out *OVNDBClusterDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNDBClusterDefaults.
func (in *OVNDBClusterDefaults) DeepCopy() *OVNDBClusterDefaults {
	if in == nil {
		return nil
	}
	out := new(OVNDBClusterDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNDBClusterList) DeepCopyInto(out *OVNDBClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OVNDBCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNDBClusterList.
func (in *OVNDBClusterList) DeepCopy() *OVNDBClusterList {
	if in == nil {
		return nil
	}
	out := new(OVNDBClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNDBClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNDBClusterOverrideSpec) DeepCopyInto(out *OVNDBClusterOverrideSpec) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(service.OverrideSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNDBClusterOverrideSpec.
func (in *OVNDBClusterOverrideSpec) DeepCopy() *OVNDBClusterOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(OVNDBClusterOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNDBClusterSpec) DeepCopyInto(out *OVNDBClusterSpec) {
	*out = *in
	in.OVNDBClusterSpecCore.DeepCopyInto(&out.OVNDBClusterSpecCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNDBClusterSpec.
func (in *OVNDBClusterSpec) DeepCopy() *OVNDBClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OVNDBClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNDBClusterSpecCore) DeepCopyInto(out *OVNDBClusterSpecCore) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.TLS.DeepCopyInto(&out.TLS)
	in.Override.DeepCopyInto(&out.Override)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNDBClusterSpecCore.
func (in *OVNDBClusterSpecCore) DeepCopy() *OVNDBClusterSpecCore {
	if in == nil {
		return nil
	}
	out := new(OVNDBClusterSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNDBClusterStatus) DeepCopyInto(out *OVNDBClusterStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkAttachments != nil {
		in, out := &in.NetworkAttachments, &out.NetworkAttachments
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNDBClusterStatus.
func (in *OVNDBClusterStatus) DeepCopy() *OVNDBClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OVNDBClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNNorthd) DeepCopyInto(out *OVNNorthd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNNorthd.
func (in *OVNNorthd) DeepCopy() *OVNNorthd {
	if in == nil {
		return nil
	}
	out := new(OVNNorthd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNNorthd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNNorthdDefaults) DeepCopyInto(out *OVNNorthdDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNNorthdDefaults.
func (in *OVNNorthdDefaults) DeepCopy() *OVNNorthdDefaults {
	if in == nil {
		return nil
	}
	out := new(OVNNorthdDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNNorthdList) DeepCopyInto(out *OVNNorthdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OVNNorthd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNNorthdList.
func (in *OVNNorthdList) DeepCopy() *OVNNorthdList {
	if in == nil {
		return nil
	}
	out := new(OVNNorthdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNNorthdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNNorthdSpec) DeepCopyInto(out *OVNNorthdSpec) {
	*out = *in
	in.OVNNorthdSpecCore.DeepCopyInto(&out.OVNNorthdSpecCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNNorthdSpec.
func (in *OVNNorthdSpec) DeepCopy() *OVNNorthdSpec {
	if in == nil {
		return nil
	}
	out := new(OVNNorthdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNNorthdSpecCore) DeepCopyInto(out *OVNNorthdSpecCore) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.TLS.DeepCopyInto(&out.TLS)
	if in.NThreads != nil {
		in, out := &in.NThreads, &out.NThreads
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNNorthdSpecCore.
func (in *OVNNorthdSpecCore) DeepCopy() *OVNNorthdSpecCore {
	if in == nil {
		return nil
	}
	out := new(OVNNorthdSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNNorthdStatus) DeepCopyInto(out *OVNNorthdStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNNorthdStatus.
func (in *OVNNorthdStatus) DeepCopy() *OVNNorthdStatus {
	if in == nil {
		return nil
	}
	out := new(OVNNorthdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVSExternalIDs) DeepCopyInto(out *OVSExternalIDs) {
	*out = *in
	if in.OvnAvailabilityZones != nil {
		in, out := &in.OvnAvailabilityZones, &out.OvnAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableChassisAsGateway != nil {
		in, out := &in.EnableChassisAsGateway, &out.EnableChassisAsGateway
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVSExternalIDs.
func (in *OVSExternalIDs) DeepCopy() *OVSExternalIDs {
	if in == nil {
		return nil
	}
	out := new(OVSExternalIDs)
	in.DeepCopyInto(out)
	return out
}
