#!/bin/bash

set -ex -o pipefail

# Always required:
#   DB_TYPE: "NB" or "SB"
#   SERVER_NAME: Name of the service exposing this server
#   OVS_DBDIR: volume mount containing databases
#
# For bootstrap:
#   BOOTSTRAP: "true"
#
# For scale up:
#   CID: cluster ID of previously initialised cluster database
#   REMOTES: Space-separated list of remote server addresses

. /dbtype.sh

if [ ! -f "$db" ]; then
    raft_address=tcp:${SERVER_NAME}:$raft_port
    if [ "$BOOTSTRAP" == "true" ]; then
        ovsdb-tool create-cluster "$db" "$schema" "$raft_address"
    else
        remotes=$(for remote in ${REMOTES}; do echo -n "tcp:$i:$raft_port "; done)
        ovsdb-tool join-cluster --cid="$CID" \
            "$db" "$db_name" "$raft_address" $remotes
    fi
fi
