---
- project:
    name: openstack-k8s-operators/ovn-operator
    github-check:
      jobs:
        - openstack-k8s-operators-content-provider:
            vars:
              cifmw_install_yamls_sdk_version: v1.41.1
        - ovn-operator-tempest-multinode
