FROM centos:centos8

ENV version=2.11
ENV release=0.6.el8ost
ENV pkg=rhosp-openvswitch
ENV brew=http://download.eng.bos.redhat.com/brewroot/vol/rhel-8/packages/

COPY fdp.repo /etc/yum.repos.d/fdp.repo
RUN dnf -y install \
    ${brew}/${pkg}/${version}/${release}/noarch/${pkg}-${version}-${release}.noarch.rpm \
    ${brew}/${pkg}/${version}/${release}/noarch/${pkg}-ovn-central-${version}-${release}.noarch.rpm \
    jq && dnf -y clean all

# We explicitly disable log output to file, but nevertheless we fail to startup
# if the files don't exist.
RUN /bin/bash -c 'touch /var/log/openvswitch/ovsdb-server-{n,s}b.log; \
                  chown -R 1000:1000 /var/log/openvswitch'

COPY scripts/* /

USER 1000:1000

VOLUME ["/var/lib/openvswitch", "/ovn-run"]
