#!/bin/bash

set -xe -o pipefail

. /image-env.sh

# Set OVN_NB_DB and OVN_SB_DB with connection info

if [ -z "${OVN_NB_DB}" -o -z "${OVN_SB_DB}" ]; then
    echo "OVN_NB_DB and OVN_SB_DB must be set" >&2
    exit 1
fi

exec /opt/bin/ovn-northd --no-chdir "-vconsole:${OVN_LOG_LEVEL}" -vfile:off
